name: Update Stock Data

on:
  schedule:
    - cron: '0 0 * * *'  # 每天午夜執行
  workflow_dispatch:      # 允許手動觸發

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0   # 獲取完整的歷史記錄
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install yfinance pandas
    
    - name: Update stock data
      run: python update_data.py
    
    - name: Configure Git
      run: |
        git config --global user.name 'GitHub Actions Bot'
        git config --global user.email 'actions@github.com'
    
    - name: Commit and push changes
      run: |
        git add stock_data/*.json
        git commit -m "chore: 更新股票數據 [skip ci]" || exit 0
        git pull --rebase origin main
        git push origin main